version: "3"

services:
  postgres:
    image: "postgres:11"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  redis:
    container_name: api_redis
    image: "redis:6.2.6-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    container_name: jobs_sidekiq
    depends_on:
      - "redis"
      - "app"
    build: .
    command: bash start_jobs.sh
    volumes:
      - ".:/ecommerce-api"
  app:
    environment:
      LC_ALL: C.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    container_name: ecommerce-api_backend
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/ecommerce-api
      - app-gems:/app-gems
    # env_file:
    #   - ".env"
    tmpfs:
      - "/tmp"
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  redis:
  postgres:
  app-gems:
